# Generated by Django 6.0.7 on 2026-08-09

import apps.projects.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_normalize_project_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.projects.storage.VercelBlobStorage(),
                upload_to="projects/",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                storage=apps.projects.storage.VercelBlobStorage(),
                upload_to="projects/gallery/",
            ),
        ),
    ]
